Update fun Bars() for Scaffold(paddingValues)
dmowski/runar-android pull request #177
Opened 2022-11-22 12:38 UTC by Evgeniy7891

Подавил требуемый обязательный параметр Scaffold (paddingValues) через аннотацию  @SuppressLint("UnusedMaterialScaffoldPaddingParameter")

2022-11-22 13:42 UTC, Valeria297 approved these changes

2022-11-22 14:56 UTC, RybinJD1 commented
https://stackoverflow.com/questions/70209466/what-is-the-purpose-of-the-paddingvalues-parameter-in-a-scaffold

2022-11-22 15:02 UTC, RybinJD1 requested changes
попробуй глянуть что тут
https://stackoverflow.com/questions/70209466/what-is-the-purpose-of-the-paddingvalues-parameter-in-a-scaffold
https://stackoverflow.com/questions/71983360/bottombar-overlays-scaffold-content-when-using-lazycolumn
аннотация с игнором такое себе решение мне кажется

2022-11-29 17:32 UTC, RybinJD1 approved these changes

2022-11-30 19:48 UTC, Valeria297 approved these changes

2022-12-01 08:52 UTC, RybinJD1 approved these changes

2022-12-01 08:52 UTC, merged