Splash Screen implemented with splash screen API.
dmowski/runar-android pull request #212
Opened 2022-12-16 12:44 UTC by inbfor

Test

2022-12-20 14:17 UTC, Valeria297 commented on app/src/main/java/com/tnco/runar/ui/activity/SplashActivity.kt
> +//    }
мб убрать файл с закомментированным кодом?

2022-12-20 14:36 UTC, Valeria297 approved these changes

2022-12-21 12:12 UTC, RybinJD1 commented on app/src/main/java/com/tnco/runar/ui/activity/SplashActivity.kt
> +//    }
это пока временная мера, чтобы легко можно было вернуть прошлую реализацию

2022-12-21 12:16 UTC, RybinJD1 commented
![image](https://user-images.githubusercontent.com/25096108/208903196-1f348705-02aa-437f-90e0-0848e1e8874c.png)

2022-12-21 15:51 UTC, RybinJD1 commented
порешай конфликты, выпили закоменченный код, и поставь 2 секунды задержку.

2022-12-21 15:56 UTC, RybinJD1 requested changes
порешай конфликты, выпили закоменченый код, и поставь 2 секунды задержку. И добавь описание для ПР

2022-12-24 22:12 UTC, Valeria297 commented
прилага падает

2022-12-25 07:58 UTC, closed without merging