Splash API on updated "main" branch without any conflicts
dmowski/runar-android pull request #220
Opened 2022-12-25 08:25 UTC by inbfor

Пересоздал ПР так как merge ломал приложение.

2022-12-26 13:49 UTC, sergey-mikhovich commented on app/src/main/java/com/tnco/runar/ui/viewmodel/MainViewModel.kt
> +    }
Зачем нам задержка в 2 секунды? Есть какие-то фоновые процессы, которые должны отработать?

2022-12-26 13:52 UTC, sergey-mikhovich commented on app/src/main/java/com/tnco/runar/ui/viewmodel/MainViewModel.kt
> +    }
Если таска связана с UI, то лучше кидать скрин того, что получилось.

2022-12-26 15:20 UTC, Valeria297 approved these changes

2022-12-26 15:21 UTC, inbfor commented on app/src/main/java/com/tnco/runar/ui/viewmodel/MainViewModel.kt
> +    }
Это вопрос к @RybinJD1 - он сказал, я сделал.

2022-12-26 16:50 UTC, sergey-mikhovich approved these changes

2022-12-26 16:51 UTC, VaritskiyArseniy approved these changes

2022-12-26 16:52 UTC, sergey-mikhovich commented on app/src/main/java/com/tnco/runar/ui/viewmodel/MainViewModel.kt
> +    }
Понял. Как по мне, слишком долго приходится ждать

2022-12-27 09:52 UTC, RybinJD1 commented on app/src/main/java/com/tnco/runar/ui/viewmodel/MainViewModel.kt
> +    }
Все зависит от производительности конкретного устройства. Бывает что сплэш появляется на доли секунды. Поэтому и 2 секунды. И да, у нас в апликейшен классе инититься много всего.

2022-12-27 09:53 UTC, RybinJD1 commented on app/src/main/AndroidManifest.xml
> -    <uses-sdk android:targetSdkVersion="33" />
Зачем удалил?

2022-12-27 09:57 UTC, RybinJD1 requested changes
верни targetSdkVersion

2022-12-27 10:52 UTC, RybinJD1 approved these changes

2022-12-27 10:53 UTC, merged