RUN-19: New design of the tabs and top bar by Figma
dmowski/runar-android pull request #223
Opened 2022-12-26 19:31 UTC by Valeria297

- Изменила дизайн табов и топ бара библиотеки согласно обновленному дизайну в фигме.
- Прорефакторила код 

До:
![скрин1](https://user-images.githubusercontent.com/90146704/209578564-2388bddd-30ec-4294-9a12-49fbd7693969.jpg)

После:
![скрин2](https://user-images.githubusercontent.com/90146704/209578566-eb0ad58e-7369-4465-bd3f-a03f5c6003f0.jpg)

2022-12-27 06:51 UTC, inbfor approved these changes

2022-12-27 07:00 UTC, sergey-mikhovich approved these changes

2022-12-27 10:05 UTC, RybinJD1 commented
![image](https://user-images.githubusercontent.com/25096108/209650188-75e62c3f-66e4-43df-9a62-8d5f7906d752.png)

2022-12-27 10:13 UTC, RybinJD1 commented on app/src/main/java/com/tnco/runar/ui/fragment/LibraryTabsCompose.kt
> +        indicator = {}
Здесь должно быть пусто?

2022-12-27 10:16 UTC, RybinJD1 requested changes
подправь плиз

2022-12-27 21:05 UTC, Valeria297 commented on app/src/main/java/com/tnco/runar/ui/fragment/LibraryTabsCompose.kt
> +        indicator = {}
да.  если мы этот код совсем уберем, то компоуз автоматически обработает индикатор в пейджере, и он будет отображаться, а нам нужно, чтобы индикатор не отображался.

2023-01-03 15:54 UTC, RybinJD1 approved these changes

2023-01-03 15:55 UTC, merged