audio switcher with di
dmowski/runar-android pull request #255
Opened 2023-01-31 16:51 UTC by Valeria297

Переделываю старый вариант реализации свитчера, который включает/выключает аудиосказки, под изменения проекта с di

2023-02-01 21:57 UTC, RybinJD1 approved these changes

2023-02-02 05:56 UTC, sergey-i-am requested changes

2023-02-02 05:56 UTC, sergey-i-am commented on app/src/main/java/com/tnco/runar/ui/viewmodel/LibraryViewModel.kt
> +    fun audioState(audioSw: DeveloperSwitcher?): Boolean {
не могу понять идею, зачем отдельная функция, почему в компоузе нельзя обратиться к стейт полю свитчера?
вот так:
if (tabsState.value && audioFeature && audioSw?.state == true) {

2023-02-02 05:56 UTC, sergey-i-am commented on app/src/main/java/com/tnco/runar/ui/viewmodel/LibraryViewModel.kt
> +            it.name == "Audio fairy tales displaying"
лучше использовать константу

2023-02-02 05:56 UTC, sergey-i-am commented on app/src/main/java/com/tnco/runar/ui/fragment/LibraryCompose.kt
> +    val audioSw by viewModel.audioSwitcher.asLiveData().observeAsState()
тут тоже по неймингу, лучше не сокращать без сильной необходимости названия, это усложняет чтение кода другими разрабами, audioSwitcher тут вполне хорошо смотрелся бы

2023-02-02 05:56 UTC, sergey-i-am commented on app/src/main/java/com/tnco/runar/repository/data_store/DataStorePreferences.kt
> +        const val AUDIO_SWITCH = "Audio fairy tales displaying"
предлагаю подумать с неймингом переменной, может что-то типа AUDIO_SWITCHER_NAME?

2023-02-04 10:59 UTC, RybinJD1 commented on app/src/main/java/com/tnco/runar/ui/viewmodel/LibraryViewModel.kt
> +            it.name == "Audio fairy tales displaying"
@Valeria297 тем более она уже есть, AUDIO_SWITCHER_NAME

2023-02-04 11:35 UTC, Valeria297 commented on app/src/main/java/com/tnco/runar/ui/viewmodel/LibraryViewModel.kt
> +            it.name == "Audio fairy tales displaying"
> @Valeria297 тем более она уже есть, AUDIO_SWITCHER_NAME

Когда использовала константу с преференсов прилага падала с ошибкой "нет элемента с таким именем в списке"

2023-02-06 13:36 UTC, RybinJD1 approved these changes

2023-02-06 14:56 UTC, RybinJD1 commented on app/src/main/java/com/tnco/runar/ui/viewmodel/LibraryViewModel.kt
> +            it.name == "Audio fairy tales displaying"
это странно

2023-02-07 08:19 UTC, RybinJD1 commented on app/src/main/java/com/tnco/runar/ui/viewmodel/LibraryViewModel.kt
> +            it.name == "Audio fairy tales displaying"
@Valeria297 обнови ветку
@sergey-i-am апрувни Пр, если нет замечаний

2023-02-07 09:19 UTC, sergey-i-am commented on app/src/main/java/com/tnco/runar/ui/viewmodel/LibraryViewModel.kt
> +            it.name == "Audio fairy tales displaying"
ну вопрос остался с этой константой что-то порешать

2023-02-08 20:02 UTC, closed without merging