RUN-223/ (Fixed toast) returned to observeOnce and add delay for loading images
dmowski/runar-android pull request #257
Opened 2023-02-02 18:04 UTC by Evgeniy7891

1. Создал двойную подписку на статус соединения с интернетом и загрузками изображений в меню библиотеки.
2. Добавил задержку показа toast -а.

2023-02-03 14:39 UTC, dmowski requested changes

2023-02-03 14:39 UTC, dmowski commented on app/src/main/java/com/tnco/runar/ui/fragment/LibraryFragment.kt
> +const val DELAY_FOR_LOADING = 600L
а мож додсказать зачем назадержка? Почему не сразу показывать?

2023-02-03 14:39 UTC, dmowski commented on app/src/main/java/com/tnco/runar/ui/fragment/LibraryFragment.kt
> +                    if (viewModel.isOnline.value == false && viewModel.errorLoad.value == true) {
Лучше написать так

```
if (!viewModel.isOnline.value && viewModel.errorLoad.value) {
```

2023-02-03 14:39 UTC, dmowski commented on app/src/main/java/com/tnco/runar/ui/fragment/LibraryFragment.kt
> +                        toast.cancel()
А зачем тост закрывать?

2023-02-04 10:53 UTC, RybinJD1 commented on app/src/main/java/com/tnco/runar/ui/fragment/LibraryFragment.kt
> +const val DELAY_FOR_LOADING = 600L
@Evgeniy7891 задержка, действительно, не нужна. Здесь дело в жизненном цикле фрагмента. Тебе нужно твой тост инитеть в в onViewCreated()

2023-02-04 10:55 UTC, RybinJD1 commented on app/src/main/java/com/tnco/runar/ui/fragment/LibraryFragment.kt
> +                        toast.cancel()
@Evgeniy7891 Да, закрывать не нужно. Не критично, если юзер перепрыгнул на другую страницу и продолжает видеть сообщение. Он должен успеть его прочитать.

2023-02-04 10:56 UTC, RybinJD1 commented on app/src/main/java/com/tnco/runar/ui/fragment/LibraryFragment.kt
> +                CoroutineScope(Dispatchers.Main).launch {
а зачем тост в корутине запускать?

2023-02-05 08:50 UTC, Evgeniy7891 commented on app/src/main/java/com/tnco/runar/ui/fragment/LibraryFragment.kt
> +const val DELAY_FOR_LOADING = 600L
Ок. Просто, на сколько я понял, были пожелания, что б не сразу выскакивал тост. Так на пример в андройд 12 он выскакивал пулей.

2023-02-05 08:54 UTC, Evgeniy7891 commented on app/src/main/java/com/tnco/runar/ui/fragment/LibraryFragment.kt
> +                        toast.cancel()
Это остаточная логика от предпоследнего ПР, я там использовал обычный observe. И если бы не закрывал, то тосты могли выскакивать по несколько штук подряд. Сейчас observeOnce и скорей всего да, тут эта логика будет лишней и не обязательной.

2023-02-05 08:55 UTC, Evgeniy7891 commented on app/src/main/java/com/tnco/runar/ui/fragment/LibraryFragment.kt
> +                CoroutineScope(Dispatchers.Main).launch {
Что б воспроизвести ту самую задержку показа.

2023-02-05 09:26 UTC, Evgeniy7891 commented on app/src/main/java/com/tnco/runar/ui/fragment/LibraryFragment.kt
> +const val DELAY_FOR_LOADING = 600L
override fun onViewCreated(view: View, savedInstanceState: Bundle?) {

        val noInternet = getString(R.string.internet_conn_error1)
        viewModel.isOnline.observeOnce(viewLifecycleOwner) {
            viewModel.errorLoad.observeOnce(viewLifecycleOwner) {
                if (viewModel.isOnline.value == false && viewModel.errorLoad.value == true) {
                    Toast.makeText(requireContext(), noInternet, Toast.LENGTH_LONG).show()
                }
            }
            super.onViewCreated(view, savedInstanceState)
        }
    }

2023-02-05 09:27 UTC, Evgeniy7891 commented on app/src/main/java/com/tnco/runar/ui/fragment/LibraryFragment.kt
> +                        toast.cancel()
if (viewModel.isOnline.value == false && viewModel.errorLoad.value == true) {
                    Toast.makeText(requireContext(), noInternet, Toast.LENGTH_LONG).show()
                }

2023-02-05 09:28 UTC, Evgeniy7891 commented on app/src/main/java/com/tnco/runar/ui/fragment/LibraryFragment.kt
> +                CoroutineScope(Dispatchers.Main).launch {
Корутину убрал

2023-02-05 09:29 UTC, Evgeniy7891 commented on app/src/main/java/com/tnco/runar/ui/fragment/LibraryFragment.kt
> +                    if (viewModel.isOnline.value == false && viewModel.errorLoad.value == true) {
Данный синтаксис не совсем подошел.

2023-02-06 09:03 UTC, RybinJD1 commented on app/src/main/java/com/tnco/runar/ui/fragment/LibraryFragment.kt
> +                    if (viewModel.isOnline.value == false && viewModel.errorLoad.value == true) {
@Evgeniy7891 а что значит не подошел?  viewModel.isOnline.value и  viewModel.errorLoad.value возвращают boolean ведь? ты может забыл поставить ! перед viewModel.isOnline.value?

2023-02-06 10:26 UTC, Evgeniy7891 commented on app/src/main/java/com/tnco/runar/ui/fragment/LibraryFragment.kt
> +                    if (viewModel.isOnline.value == false && viewModel.errorLoad.value == true) {
1. Добавить оператор safe call или поставить !! что б не проверял на null. 
![2023-02-06_14-24-58](https://user-images.githubusercontent.com/99983028/216947736-903a6bd9-7da9-4ce3-b7d2-066c6e075e0d.png)

2023-02-06 10:28 UTC, Evgeniy7891 commented on app/src/main/java/com/tnco/runar/ui/fragment/LibraryFragment.kt
> +                    if (viewModel.isOnline.value == false && viewModel.errorLoad.value == true) {
2. Во втором случаи он сам подсказывает добавить конкретику для проверки. 
![2023-02-06_14-27-09](https://user-images.githubusercontent.com/99983028/216948207-b22d084a-6832-49d8-bce9-f1710970a68c.png)

2023-02-06 10:30 UTC, Evgeniy7891 commented on app/src/main/java/com/tnco/runar/ui/fragment/LibraryFragment.kt
> +                    if (viewModel.isOnline.value == false && viewModel.errorLoad.value == true) {
3. в if нужна определенность в проверке, это не как в блоке when(), где по-любому отрабатывает только true

2023-02-06 11:04 UTC, RybinJD1 commented on app/src/main/java/com/tnco/runar/ui/fragment/LibraryFragment.kt
> +                    if (viewModel.isOnline.value == false && viewModel.errorLoad.value == true) {
да, вижу что value это @Nullable функция. ок оставляем так

2023-02-06 11:04 UTC, RybinJD1 approved these changes

2023-02-06 13:32 UTC, dmowski approved these changes

2023-02-06 13:33 UTC, merged