Run 301
dmowski/runar-android pull request #267
Opened 2023-02-10 19:14 UTC by Gregorioous

## Описание 📝
Добавлен блюр под панель навигации 

### На что стоит обратить внимание при ревью 👀
За время выполнения задачи было просмотрено более 20 библиотек с эффектом блюра и нормально работала по итогу только одна

---

### Скриншоты экранов 📺 🖥
![image_2023-02-09_14-32-07](https://user-images.githubusercontent.com/106704479/218177871-439fbe47-3ba9-4181-96c8-64b560744dff.png)

---

### Чеклист проверки ✅

- [ ] Проверил на разных экранах
- [ ] Проверил на разных версиях ос
- [ ] Изображения оптимизированы
- [ ] Readme актуальный

2023-02-11 04:44 UTC, sergey-i-am commented on app/src/main/res/layout/activity_main.xml
> +        android:background="#D8000000"
зачем захардкодил?

2023-02-11 04:51 UTC, sergey-i-am commented on build.gradle
> +        jcenter()
он депрекейтед, выше строкой мейвенцентрал, как раз на замену ему

2023-02-11 05:23 UTC, sergey-i-am commented on app/src/main/res/layout/activity_main.xml
> +
?

2023-02-11 05:41 UTC, sergey-i-am requested changes

2023-02-11 05:41 UTC, sergey-i-am commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_height="match_parent"
https://developer.android.com/reference/androidx/constraintlayout/widget/ConstraintLayout

> Important: MATCH_PARENT is not recommended for widgets contained in a ConstraintLayout. Similar behavior can be defined by using MATCH_CONSTRAINT with the corresponding left/right or top/bottom constraints being set to "parent".
> Using 0dp, which is the equivalent of "MATCH_CONSTRAINT"

2023-02-11 05:41 UTC, sergey-i-am commented on app/src/main/res/layout/activity_main.xml
> +
?

2023-02-12 08:03 UTC, Gregorioous commented on build.gradle
> +        jcenter()
если убрать jcenter то либа не работает, поэтому его нужно оставить

2023-02-12 13:05 UTC, sergey-i-am commented on build.gradle
> +        jcenter()
может не стоит ее брать тогда? это какой то костыль будет
@RybinJD1 что думаешь?

2023-02-13 15:21 UTC, dmowski commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:7.4.0'
возможно это изменени привело к падению CI/CD?
оно точно нужно?

2023-02-14 22:23 UTC, closed without merging