rebase_didn't_work_so_i_made_a_new_branch
dmowski/runar-android pull request #276
Opened 2023-02-17 07:18 UTC by Gregorioous

## Описание 📝
Так как при rebase возникало слишком много конфликтов - мне посоветовали сделать новую ветку с изменениями которые сделал дима в своей задаче 

### На что стоит обратить внимание при ревью 👀

---

### Скриншоты экранов 📺 🖥

---

### Чеклист проверки ✅

- [ ] Проверил на разных экранах
- [ ] Проверил на разных версиях ос
- [ ] Изображения оптимизированы
- [ ] Readme актуальный

2023-02-17 09:10 UTC, sergey-i-am requested changes

2023-02-17 09:10 UTC, sergey-i-am commented on app/src/main/java/com/tnco/runar/ui/activity/MainActivity.kt
вот это не надо трогать

2023-02-17 09:10 UTC, sergey-i-am commented on app/src/main/java/com/tnco/runar/ui/activity/MainActivity.kt
>      }
это тоже не входит в твою задачу

2023-02-17 09:18 UTC, sergey-i-am commented
когда мержишь изменения, не надо перезатирать чужие коммиты, ты просто взял перезаписал поверх чужого кода версию этих строк из своей устаревшей мейн ветки, возможно поэтому у тебя и тест упал

когда сливаешь, смотри какой код в мейн ветке ты не трогал и его и оставляй в таком виде, а там, где ты что-то менял, то аккуратно заменяй своим новым

если за время пока ты делал таску этот код тоже кто-то вдруг поменял, то нужно смотреть как теперь слить, чтобы ничего не сломать, если что не очень понятно, попроси помощи у автора этого коммита, и вместе решите как правильно

2023-02-20 05:28 UTC, sergey-i-am submitted a review, later dismissed

2023-02-20 07:11 UTC, sergey-i-am commented on app/src/main/java/com/tnco/runar/ui/activity/SplashActivity.kt
> +        Intent(this, MainActivity::class.java).apply {
онбординг теперь вообще не показывается, вне зависимости от положения свитчера в настройках, так и было задумано разве?

2023-02-20 07:18 UTC, sergey-i-am commented on app/src/main/java/com/tnco/runar/ui/activity/SplashActivity.kt
> +        Intent(this, MainActivity::class.java).apply {
видимо потому и тест не проходит, что никакого онбординга нет

2023-02-20 09:11 UTC, Gregorioous commented on app/src/main/java/com/tnco/runar/ui/activity/SplashActivity.kt
> +        Intent(this, MainActivity::class.java).apply {
это были изменения которые внёс дима когда делал это задание, ок исправлю

2023-02-27 01:11 UTC, closed without merging