Run 307
dmowski/runar-android pull request #290
Opened 2023-03-18 17:01 UTC by Gregorioous

## Описание 📝
Изменены шрифт и цвет заголовков раздела «Генератор».
### На что стоит обратить внимание при ревью 👀

---

### Скриншоты экранов 📺 🖥

---

### Чеклист проверки ✅

- [ ] Проверил на разных экранах
- [ ] Проверил на разных версиях ос
- [ ] Изображения оптимизированы
- [ ] Readme актуальный

2023-03-19 08:56 UTC, VaritskiArseniy approved these changes

2023-03-20 04:45 UTC, sergey-i-am requested changes

2023-03-20 04:45 UTC, sergey-i-am commented on app/src/main/res/layout-hdpi/fragment_generator_start.xml
> +        <RelativeLayout
зачем нам тут RelativeLayout? он устарел и его уже не рекомендуется использовать, да и в целом не пойму что он тут делает?

2023-03-20 04:45 UTC, sergey-i-am commented on app/src/main/res/layout-sw600dp/fragment_generator_start.xml
> +        <RelativeLayout
и тут

2023-03-20 04:45 UTC, sergey-i-am commented on app/src/main/res/layout-xhdpi/fragment_generator_start.xml
> +        app:layout_constraintGuide_begin="91dp" />
почему меняем относительный на абсолютный?

2023-03-20 08:27 UTC, sergey-i-am approved these changes

2023-03-20 10:55 UTC, merged